TrajectoryPlannerROS:
  max_vel_x: 0.3
  min_vel_x: 0.1
  max_vel_theta: 1.0
  min_vel_theta: -1.0
  acc_lim_theta: 3.2
  acc_lim_x: 2.5
  acc_lim_y: 0.0

  sim_time: 1.0
  sim_granularity: 0.025
  goal_distance_bias: 0.8
  path_distance_bias: 0.6
  occdist_scale: 0.01

  heading_lookahead: 0.325
  dwa: true