local_costmap:
  global_frame: odom # 고정
  robot_base_frame: base_footprint # 고정
  update_frequency: 15.0  
  publish_frequency: 5.0
  rolling_window: true
  width: 8.0
  height: 8.0
  resolution: 0.05

  plugins:
    - {name: obstacle_layer,  type: "costmap_2d::ObstacleLayer"}
    - {name: inflation_layer, type: "costmap_2d::InflationLayer"}

  obstacle_layer:
    observation_sources: scan
    scan:
      data_type: LaserScan
      topic: /scan
      marking: true
      clearing: true
      expected_update_rate: 0.1
      observation_persistence: 0.5
    track_unknown_space: false  

  inflation_layer:
    inflation_radius: 0.35  # 너무 크면 장애물로 인식하는 범위가 넓어져 경로 생성 불가능, 반면에 너무 작으면 충돌 가능성이 높아 적정 파라미터는 환경마다 다르게 세팅
    cost_scaling_factor: 3.0
