joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50  

# Position Controllers ---------------------------------------
left_wheel_controller:
  type: effort_controllers/JointPositionController
  joint: left_wheel_joint
  pid: {p: 1.0, i: 0.1, d: 0.01}
right_wheel_controller:
  type: effort_controllers/JointPositionController
  joint: right_wheel_joint
  pid: {p: 1.0, i: 0.1, d: 0.01}