# RegulatedPurePursuitController:
  desired_linear_vel: 0.3   # The desired maximum linear velocity (m/s) to use.
  lookahead_dist: 0.4   # The lookahead distance (m) to use to find the lookahead point when use_velocity_scaled_lookahead_dist is false.
  min_lookahead_dist: 0.3   # The lookahead distance (m) to use to find the lookahead point when use_velocity_scaled_lookahead_dist is false.
  max_lookahead_dist: 0.7   # The maximum lookahead distance (m) threshold when use_velocity_scaled_lookahead_dist is true.
  lookahead_time: 1.5   # The time (s) to project the velocity by when use_velocity_scaled_lookahead_dist is true. Also known as the lookahead gain.
  rotate_to_heading_angular_vel: 1.8   # If use_rotate_to_heading is true, this is the angular velocity to use.
  transform_tolerance: 0.25   # The TF transform tolerance (s).
  use_velocity_scaled_lookahead_dist: True   # Whether to use the velocity scaled lookahead distances or constant lookahead_distance.
  min_approach_linear_velocity: 0.05   # The minimum velocity (m/s) threshold to apply when approaching the goal to ensure progress. Must be > 0.01.
  approach_velocity_scaling_dist: 0.6   # The distance (m) left on the path at which to start slowing down. Should be less than the half the costmap width.
  use_collision_detection: true   # Whether to enable collision detection.
  max_allowed_time_to_collision_up_to_carrot: 3.0   # The time (s) to project a velocity command forward to check for collisions when use_collision_detection is true. Pre-Humble, this was max_allowed_time_to_collision.
  use_regulated_linear_velocity_scaling: true   # Whether to use the regulated features for path curvature (e.g. slow on high curvature paths).
  use_fixed_curvature_lookahead: false   # Whether to use a fixed lookahead distance to compute curvature from. Since a lookahead distance may be set to vary on velocity, it can introduce a reference cycle that can be problematic for large lookahead distances.
  curvature_lookahead_dist: 0.25   # Distance to look ahead on the path to detect curvature.
  use_cost_regulated_linear_velocity_scaling: true   # Whether to use the regulated features for proximity to obstacles (e.g. slow in close proximity to obstacles).
  regulated_linear_scaling_min_radius: 0.9   # The turning radius (m) for which the regulation features are triggered when use_regulated_linear_velocity_scaling is true. Remember, sharper turns have smaller radii.
  regulated_linear_scaling_min_speed: 0.1   # The minimum speed (m/s) for which any of the regulated heuristics can send, to ensure process is still achievable even in high cost spaces with high curvature. Must be > 0.1.
  use_rotate_to_heading: true   # Whether to enable rotating to rough heading and goal orientation when using holonomic planners. Recommended on for all robot types that can rotate in place.
                                # Note: both use_rotate_to_heading and allow_reversing cannot be set to true at the same time as it would result in ambiguous situations.
  allow_reversing: false   # Enables the robot to drive in the reverse direction, when the path planned involves reversing (which is represented by orientation cusps). Variants of the smac_planner comes with the support of reversing. Checkout the Smac Planner to know more.
  rotate_to_heading_min_angle: 0.5   # The difference in the path orientation and the starting robot orientation (radians) to trigger a rotate in place, if use_rotate_to_heading is true.
  max_angular_accel: 0.3   # Maximum allowable angular acceleration (rad/s/s) while rotating to heading, if use_rotate_to_heading is true.
  max_linear_accel: 1.5
  max_robot_pose_search_dist: 10.0
  theta_stopped_vel: 1.0
  trans_stopped_vel: 0.02
  goal_dist_tol: 0.5
  angle_tol: 0.03
  max_linear_vel: 0.3
  max_angular_vel: 0.8
  cost_scaling_dist: 0.6   # The minimum distance from an obstacle to trigger the scaling of linear velocity, if use_cost_regulated_linear_velocity_scaling is enabled. The value set should be smaller or equal to the inflation_radius set in the inflation layer of costmap, since inflation is used to compute the distance from obstacles.
  cost_scaling_gain: 1.0   # A multiplier gain, which should be <= 1.0, used to further scale the speed when an obstacle is within cost_scaling_dist. Lower value reduces speed more quickly.
  inflation_cost_scaling_factor: 3.0
  interpolate_curvature_after_goal: false   # Interpolate a carrot after the goal dedicated to the curvate calculation (to avoid oscilaltions at the end of the path). For visualization, it will be published on the /curvature_lookahead_point topic similarly to /lookahead_point
                                            # Note: Needs use_fixed_curvature_lookahead to be true
  planner_frequency: 3.0        # 2~5 Hz 권장, 글로벌 코스트맵이 바뀌면 계속 새 경로 생성
  controller_frequency: 10.0
  controller_patience: 1.0~1.5  # 로컬 제어가 막히면 빨리 포기하고 리커버리/리플랜로 전환
  recovery_enabled: true
  
  k: 6.0
  min_turning_radius: 0.2
  use_vector_pure_pursuit: false # If you want to use vector pure pursuit controller, set it "true" and follow this link https://docs.ros.org/en/humble/p/vector_pursuit_controller/
